#!/usr/bin/env python3
from subprocess import call
import sys

sys.path.append('hooks')
sys.path.append('lib')

from charmhelpers.core.hookenv import (
    action_get,
    action_set,
    status_set,
)

from charms.reactive import is_flag_set


if __name__ == "__main__":

    status_set('maintenance',
               "Re-configuring maas-url")

    maas_url = action_get('maas-url')
    if is_flag_set('maas-region.available'):
        call('maas config --maas-url {}'.format(maas_url).split())
        action_set({'maas-url': url_url})
        status_set('active', 'maas-url set to: {}'.format(maas_url))
    else:
        status_set('active', 'maas-url not set, maas-region not available')
